name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env:
  solana_verion: 1.7.12

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['yarn test']
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "${{ matrix.node }}"

      - uses: actions/cache@v2
        name: cache solana cli
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.solana_verion }}

      - uses: actions/cache@v2
        name: cache target directory
        id: cache-programs
        with:
          path: |
            ./target
          key: solana-${{ runner.os }}-v0000-${{ hashFiles('**/programs/**/*.rs') }}-${{ hashFiles('**/programs/**/*.toml') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: install essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: install solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_verion }}/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: setup solana
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new

      - name: install anchor
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g @project-serum/anchor-cli

      - name: install node_modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          yarn install --ignore-scripts

      - name: build programs
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build

      - name: run tests
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          ${{ matrix.node }}
